// src/components/Header/index.tsx
import { useEffect } from 'react';
import { routes, type RouteType } from '../../constants/routes';
import Banner from '../Banner';
import Error from '../Error';
import './Header.scss';
import { useLocation, useNavigate } from 'react-router';

export default function Header() {
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const header = document.querySelector('header');

    if (!header) {
      return;
    }

    const headerArea = document.querySelector('.header_area');
    const navOffsetTop = header.clientHeight + 50;

    if (headerArea) {
      const onScroll = () => {
        const scroll = window.scrollY;

        if (scroll >= navOffsetTop) {
          headerArea.classList.add('navbar_fixed');
        } else {
          headerArea.classList.remove('navbar_fixed');
        }
      };

      window.addEventListener('scroll', onScroll);

      return () => {
        window.removeEventListener('scroll', onScroll);
      };
    }
  }, []);

  const getCurrentRoute = (): RouteType => {
    return routes.find(item => item.path === '/' ? location.pathname === item.path : location.pathname.includes(item.path)) || {path: '/error', name: 'Not found', component: <Error mainText="Page not found" />};
  };

  const isCurrentRoute = (route: string): boolean => {
    return route === getCurrentRoute().path;
  };

  const navigateRoute = (route: string): void => {
    navigate(route);
  };

  return (
    <>
      <header className={`header_area ${isCurrentRoute('/') ? 'header-home-page' : ''}`}>
        <div className="main_menu">
          <nav className="navbar navbar-expand-lg navbar-light">
            <div className="container">
              <a className="navbar-brand" onClick={() => navigateRoute('/')}><img src="/assets/images/logo.svg" alt="David Bradshaw Home" /></a>
              <button className="navbar-toggler" id="mobile-button" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
                <span className="icon-bar"></span>
              </button>
              <div className="collapse navbar-collapse offset" id="navbarSupportedContent">
                <ul className="nav navbar-nav menu_nav justify-content-end">
                  {routes.map(route => {
                    return (
                      <li key={route.path} className={`nav-item ${isCurrentRoute(route.path) ? 'active' : ''}`}>
                        <a className="nav-link" onClick={() => navigateRoute(route.path)}>
                          <span className="nav-text">{route.name}</span>
                        </a>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <Banner currentRoute={getCurrentRoute()}/>
    </>
  );
}

// src/app/header/header.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { Router } from '@angular/router';
import { NavItem } from '../models/models';
import { SharedService } from '../services/shared.service';
import * as jquery from 'jquery';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  menuItems: Array<NavItem>;

  constructor(
    private router: Router,
    private sharedService: SharedService,
    private elementRef: ElementRef
  ) { }

  ngOnInit() {
    this.menuItems = this.sharedService.getAvailableRoutes();
    this.navbarFixed();
  }

  isActiveRoute(menuItem: NavItem): boolean {
    return this.router.url === menuItem.link;
  }

  isHomePage(): boolean {
    return this.router.url === '/';
  }

  routeClick(): void {
    const body = document.querySelector('body');
    if (body && body.clientWidth <= 991) {
      const mobileButton = this.elementRef.nativeElement.querySelector('#mobile-button');
      if (mobileButton) {
        mobileButton.click();
      }
    }
  }

  navbarFixed() {
    const navOffsetTop = jquery('header').height() + 50;
    const headerArea = jquery('.header_area');
    if (headerArea) {
      jquery(window).scroll(() => {
        const scroll = jquery(window).scrollTop();
        if (scroll >= navOffsetTop) {
          headerArea.addClass('navbar_fixed');
        } else {
          headerArea.removeClass('navbar_fixed');
        }
      });
    }
  }
}

<header class="header_area" [ngClass]="{'header-home-page': isHomePage()}">
  <div class="main_menu">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand" routerLink="/"><img src="/assets/images/logo.svg" alt="David Bradshaw Home"></a>
        <button class="navbar-toggler" id="mobile-button" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
          <ul class="nav navbar-nav menu_nav justify-content-end">
            @for (menuItem of menuItems; track menuItem) {
              <li class="nav-item" [ngClass]="{'active': isActiveRoute(menuItem)}">
                <a class="nav-link" (click)="routeClick()" [routerLink]="menuItem.link">
                  <span class="nav-text">{{menuItem.name}}</span>
                </a>
              </li>
            }
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>
<app-banner [home]="isHomePage()"></app-banner>
