// src/components/Error/index.tsx
import './Error.scss';

export default function Error(props: {mainText: string; subText?: string}) {
  return (
    <div className="error-page">
      <div className="row justify-content-center">
        <div className="col-sm-12 text-center">
          <div className="error-image"></div>
          <div className="error-main-text">{props.mainText}</div>
          {!!props.subText && <div className="error-sub-text">{props.subText}</div>}
        </div>
      </div>
    </div>
  );
}

// src/app/error/error.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-error',
    templateUrl: './error.component.html',
    styleUrls: ['./error.component.scss'],
    standalone: false
})
export class ErrorComponent {
  @Input() mainText = 'Unable to load resources';
  @Input() subText = 'The server could be experiencing issues, try refreshing the page or contacting us.';

  constructor() { }

}

<div class="container error-page">
  <div class="row justify-content-center">
    <div class="col-sm-12 text-center">
      <div class="error-image"></div>
      <div class="error-main-text">{{mainText}}</div>
      @if (subText) {
        <div class="error-sub-text">{{subText}}</div>
      }
    </div>
  </div>
</div>
