// src/components/Banner/index.tsx
import { useEffect } from 'react';
import type { RouteType } from '../../constants/routes';
import './Banner.scss';
import { useLocation, useNavigate } from 'react-router';

let imageNumber = 1;

export default function Banner(props: {currentRoute: RouteType}) {
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    imageNumber = Math.floor(Math.random() * 3);
  }, []);

  const scrollDown = (): void => {
    const image = document.querySelector('#fullscreen-image');

    if (image) {
      window.scrollTo({
        top: image.clientHeight - 20,
        behavior: 'smooth'
      });
    }
  };

  const clickableTitle = location.pathname !== props.currentRoute.path;

  if (props.currentRoute.path === '/') {
    return (
      <section className="banner-area owl-carousel" id="home">
        <div className={`single_slide_banner slide_bg image-${imageNumber}`}>
          <div className="container">
            <div className="row fullscreen d-flex align-items-center" id="fullscreen-image" style={{height: `${window.innerHeight}px`}}>
              <div className="banner-content col-lg-12 justify-content-center">
                <h1>David Bradshaw</h1>
                <h3>Software Engineer and UX Designer</h3>
                <a onClick={scrollDown} className="primary-btn">
                  <i className="fa fa-arrow-down" style={{marginRight: '5px'}}></i>
                  Learn more
                  <i className="fa fa-arrow-down" style={{marginLeft: '5px'}}></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
    );
  } else {
    return (
      <section className="banner_area">
        <div className="banner_inner d-flex align-items-center">
          <div className="container">
            <div className="banner_content text-right">
              <h1>{clickableTitle ? <a onClick={() => navigate(props.currentRoute.path)}>{props.currentRoute.name}</a> : props.currentRoute.name}</h1>
            </div>
          </div>
        </div>
      </section>
    );
  }
}

// src/app/banner/banner.component.ts
import { Component, Input } from '@angular/core';
import { SharedService } from '../services/shared.service';
import { Router } from '@angular/router';
import jquery from 'jquery';

@Component({
    selector: 'app-banner',
    templateUrl: './banner.component.html',
    styleUrls: ['./banner.component.scss'],
    standalone: false
})
export class BannerComponent {
  @Input() home: boolean;
  imageNumber = 1;

  constructor(
    private sharedService: SharedService,
    private router: Router
  ) {
    this.imageNumber = Math.floor(Math.random() * 3);
   }

  getWindowHeight(): string {
    return window.innerHeight + 'px';
  }

  getCurrentPageName(): string {
    return this.sharedService.getCurrentPage().name;
  }

  scrollDown(): void {
    jquery('html, body').animate({
      scrollTop: (jquery('#fullscreen-image')[0].offsetHeight - 20)
    }, 500);
  }

  hasNavigationLink(): boolean {
    return this.router?.url?.split('/')?.length > 2;
  }

  navigateToPage(): void {
    if (this.hasNavigationLink()) {
      const parentPath = this.router.url.split('/')[1];
      this.router.navigate([parentPath]);
    }
  }
}

@if (!home) {
  <section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
      <div class="container">
        <div class="banner_content text-right">
          <h1 class="{{hasNavigationLink() ? 'banner_quick_jump' : ''}}" (click)="navigateToPage()">{{getCurrentPageName()}}</h1>
        </div>
      </div>
    </div>
  </section>
}

@if (home) {
  <section class="banner-area owl-carousel" id="home">
    <div class="single_slide_banner slide_bg image-{{imageNumber}}">
      <div class="container">
        <div class="row fullscreen d-flex align-items-center" id="fullscreen-image" [ngStyle]="{height: getWindowHeight()}">
          <div class="banner-content col-lg-12 justify-content-center">
            <h1>David Bradshaw</h1>
            <h3>Software Engineer and UX Designer</h3>
            <a (click)="scrollDown()" class="primary-btn">
              <i class="fa fa-arrow-down" style="margin-right: 5px;"></i>
              Learn more
              <i class="fa fa-arrow-down" style="margin-left: 5px;"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
}
