// src/app/contact/contact.component.ts
import { Component, OnInit, ElementRef } from '@angular/core';
import { SharedService } from '../services/shared.service';
import { ContactForm } from '../models/models';
import { ApiService } from '../services/api.service';

@Component({
    selector: 'app-contact',
    templateUrl: './contact.component.html',
    styleUrls: ['./contact.component.scss'],
    standalone: false
})
export class ContactComponent implements OnInit {
  formData: ContactForm = new ContactForm();
  sendEmailConfirm = false;
  disableForm = false;

  constructor(
    private sharedService: SharedService,
    private elementRef: ElementRef,
    private apiService: ApiService
  ) { }

  ngOnInit() {
    this.sharedService.setPageTitle('Contact me');
    this.sharedService.setCurrentPage(this.sharedService.getNavItemByRoute('/contact'));
    this.sharedService.setCurrentBreadcrumbs([
      this.sharedService.getNavItemByRoute('/'),
      this.sharedService.getNavItemByRoute('/contact')
    ]);
  }

  sendContact(): void {
    const emailTest = prompt('Please confirm your email address');

    if (emailTest.toLowerCase() !== this.formData.email.toLowerCase()) {
      alert('Emails do not match. Please try again.');
      return;
    }

    const data = {
      from: this.formData.name,
      email: this.formData.email,
      _subject: `[David Website]: ${this.formData.subject}`,
      message: this.formData.message,
      sent: new Date().toISOString(),
    };
    this.disableForm = true;
    this.apiService.post('https://mailthis.to/emaildavid', data, {responseType: 'text'}).subscribe({
      next: () => {
        alert('To confirm you are not a robot.  Please do the following captcha and then click "Go Back" to return.');
        this.formData = new ContactForm();
        this.disableForm = false;
        window.location.href = 'https://mailthis.to/confirm';
      },
      error: error => {
        alert('Message could not be sent. Please try again.');
        this.sharedService.handleError('Unable to submit contact form', error);
        this.disableForm = false;
      }
    });
  }

  formDisabled(): boolean {
    if (
      this.formData.name &&
      this.formData.email &&
      this.formData.message &&
      this.formData.subject &&
      this.sharedService.isValidEmail(this.formData.email) &&
      !this.disableForm
    ) {
      return false;
    }
    return true;
  }

}

<section class="contact_area section_gap">
  <div class="container">
      <div class="row">
          <div class="col-lg-4">
              <div class="contact_info">
                  <div class="info_item">
                      <i class="fa fa-home"></i>
                      <h6>Silicon Valley</h6>
                      <p>Santa Clara</p>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="contact_info">
                  <div class="info_item">
                      <i class="fa fa-envelope"></i>
                      <h6>Send a message</h6>
                      <p>Send me an email or LinkedIn message</p>
                  </div>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="contact_info">
                  <div class="info_item">
                    <i class="fa fa-linkedin"></i>
                    <h6>Connect on LinkedIn</h6>
                    <p>Connect or message me via <a href="https://linkedin.com/in/davidbradshawus" target="_blank" title="LinkedIn">LinkedIn</a></p>
                </div>
              </div>
          </div>
      </div>
      <div class="mapBox">
        <div class="gmap_canvas">
          <iframe class="gmap_iframe" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?output=embed&ll=37.397617,-121.960823&z=11"></iframe>
        </div>
      </div>
  </div>
</section>

// src/views/Contact/index.tsx
import './Contact.scss';

export default function Contact() {
  return (
    <section className="contact_area section_gap">
      <div className="container">
        <div className="row">
          <div className="col-lg-4">
            <div className="contact_info">
              <div className="info_item">
                <i className="fa fa-home"></i>
                <h6>Silicon Valley</h6>
                <p>Santa Clara</p>
              </div>
            </div>
          </div>
          <div className="col-lg-4">
            <div className="contact_info">
              <div className="info_item">
                <i className="fa fa-envelope"></i>
                <h6>Send a message</h6>
                <p>Send me an email or LinkedIn message</p>
              </div>
            </div>
          </div>
          <div className="col-lg-4">
            <div className="contact_info">
              <div className="info_item">
                <i className="fa fa-linkedin"></i>
                <h6>Connect on LinkedIn</h6>
                <p>Connect or message me via <a href="https://linkedin.com/in/davidbradshawus" target="_blank" title="LinkedIn">LinkedIn</a></p>
              </div>
            </div>
          </div>
        </div>
        <div className="mapBox">
          <div className="gmap_canvas">
            <iframe className="gmap_iframe" width="100%" frameBorder="0" scrolling="no" marginHeight={0} marginWidth={0} src="https://maps.google.com/maps?output=embed&ll=37.397617,-121.960823&z=11"></iframe>
          </div>
        </div>
      </div>
    </section>
  );
}
