// src/app/loading/loading.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-loading',
    templateUrl: './loading.component.html',
    styleUrls: ['./loading.component.scss'],
    standalone: false
})
export class LoadingComponent {

  constructor() { }
}

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-12 text-center">
      <div class="spinner-border loading-indication" title="Loading"></div>
    </div>
  </div>
</div>

// src/components/Loading/index.tsx
import './Loading.scss';

export default function Loading() {
  return (
    <div className="container">
      <div className="row justify-content-center">
        <div className="col-sm-12 text-center">
          <div className="spinner-border loading-indication" title="Loading"></div>
        </div>
      </div>
    </div>
  );
}
