// src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  ngOnInit() {}

  getYear(): number {
    return new Date().getFullYear();
  }
}

<footer class="footer_area section_gap">
  <div class="container">
    <div class="row footer_inner justify-content-center">
      <div class="col-lg-6 text-center">
        <aside class="f_widget social_widget">
          <div class="f_logo">
            <img src="/assets/images/logo.svg" alt="David Bradshaw">
          </div>
          <div class="f_title">
            <h4>Follow Me</h4>
          </div>
          <ul class="list">
            <li><a href="https://linkedin.com/in/davidbradshawus" target="_blank" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://github.com/dabrad26" target="_blank" title="Github"><i class="fa fa-github"></i></a></li>
            <li><a href="https://www.facebook.com/dabrad26" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://twitter.com/dabrad26" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
          </ul>
        </aside>
        <div class="copyright">
          <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;{{getYear()}} David Bradshaw. All rights reserved.<br>
            This template is made by <a href="https://colorlib.com" target="_blank">Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

// src/components/Footer/index.tsx
import './Footer.scss';

export default function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="footer_area section_gap">
      <div className="container">
        <div className="row footer_inner justify-content-center">
          <div className="col-lg-6 text-center">
            <aside className="f_widget social_widget">
              <div className="f_logo">
                <img src="/assets/images/logo.svg" alt="David Bradshaw" />
              </div>
              <div className="f_title">
                <h4>Follow me</h4>
              </div>
              <ul className="list">
                <li><a href="https://linkedin.com/in/davidbradshawus" target="_blank" title="LinkedIn"><i className="fa fa-linkedin"></i></a></li>
                <li><a href="https://instagram.com/dabrad26" target="_blank" title="Instagram"><i className="fa fa-instagram"></i></a></li>
                <li><a href="https://github.com/dabrad26" target="_blank" title="Github"><i className="fa fa-github"></i></a></li>
              </ul>
            </aside>
            <div className="copyright">
              <p>
              Copyright &copy;{currentYear} David Bradshaw. All rights reserved.<br />
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
