// src/views/Resume/index.tsx
import React, { useEffect, useState, type MouseEvent } from 'react';
import './Resume.scss';
import Loading from '../../components/Loading';
import Error from '../../components/Error';
import type { AwardItem, EducationItem, ExperienceItem } from '../../constants/models';

export default function Resume() {
  const [status, setStatus] = useState('loading');
  const [experiences, setExperiences] = useState([] as ExperienceItem[]);
  const [showAllExperience, setShowAllExperience] = useState(false);
  const [educations, setEducations] = useState([] as EducationItem[]);
  const [showAllEducation, setShowAllEducation] = useState(false);
  const [certificates, setCertificates] = useState([] as EducationItem[]);
  const [showAllCertificates, setShowAllCertificates] = useState(false);
  const [awards, setAwards] = useState([] as AwardItem[]);
  const [showAllAwards, setShowAllAwards] = useState(false);

  useEffect(() => {
    const promises = [
      fetch('/assets/api/educations.json').then(response => response.json()).then(data => setEducations(data)),
      fetch('/assets/api/experiences.json').then(response => response.json()).then(data => setExperiences(data)),
      fetch('/assets/api/certificates.json').then(response => response.json()).then(data => setCertificates(data)),
      fetch('/assets/api/awards.json').then(response => response.json()).then(data => setAwards(data)),
    ];

    Promise.all(promises).then(() => {
      setStatus('ready');
    }).catch(error => {
      console.error('Resume: unable to get data', error);
      setStatus('error');
    });
  }, []);

  const getDateStringValue = (date: string): string => {
    return new Date(date).toLocaleDateString('en-us', {year: 'numeric', month: 'short'});
  };

  const getDateString = (startDate: string, endDate?: string|null): string => {
    return `${getDateStringValue(startDate)} - ${endDate ? getDateStringValue(endDate) : 'Present'}`;
  };

  const handleShowMore = (event: MouseEvent, callback: (value: boolean) => void): void => {
    event.preventDefault();
    callback(true);
  };

  const getEducationView = (title: string, items: EducationItem[], showAll: boolean, setShowCallback: (value: boolean) => void): React.ReactNode => {
    return (
      <div className="row justify-content-center resume-grouping">
        <div className="col-md-4 padded-right">
          <div className="section-title main-title">
            <h1>{title}</h1>
          </div>
        </div>
        <div className="col-md-8">
          {items.map((education, index) => {
            return (
              <div key={`${title}-${index}`}>
                <div className={`listing ${education.collapsed && !showAll ? 'collapsed-item' : ''}`}>
                  <div className="listing-title">
                    <span>{education.degree} {education.program ? 'in' : ''} {education.program}</span>
                    {!education.endDate && <i className="fa fa-asterisk listing-note" title="In progress"></i>}
                  </div>
                  <div className="listing-subtitle">{education.school}, {education.location}; {getDateString(education.startDate, education.endDate)}</div>
                  <div className="listing-description">{education.description}</div>
                </div>
              </div>
            );
          })}
          {!showAll && <a href="" onClick={event => handleShowMore(event, setShowCallback)}>Show more</a>}
        </div>
      </div>
    );
  };

  const getMainView = (): React.ReactNode => {
    switch (status) {
    case 'loading':
      return <Loading />;
    case 'error':
      return <Error mainText="Unable to get data" />;
    default:
      return (
        <>
          <div className="row justify-content-center resume-grouping">
            <div className="col-md-4 padded-right">
              <div className="section-title main-title">
                <h1>Experience</h1>
              </div>
            </div>
            <div className="col-md-8">
              {experiences.map((experience, index) => {
                return (
                  <div key={`experience-${index}`}>
                    <div className={`listing ${experience.collapsed && !showAllExperience ? 'collapsed-item' : ''}`}>
                      <div className="listing-title">{experience.jobTitle}</div>
                      <div className="listing-subtitle">{experience.company}, {experience.location}; {getDateString(experience.startDate, experience.endDate)}</div>
                      {!!experience.roles && (
                        <div className="listing-roles">
                          {experience.roles.map((role, roleIndex) => <div key={`experience-role-${roleIndex}`} className="listing-roles--item">{getDateString(role.startDate, role.endDate)} &mdash; {role.jobTitle}</div>)}
                        </div>
                      )}
                      <div className="listing-description">{experience.description}</div>
                    </div>
                  </div>
                );
              })}
              {!showAllExperience && <a href="" onClick={event => handleShowMore(event, setShowAllExperience)}>Show more</a>}
            </div>
          </div>
          {getEducationView('Education', educations, showAllEducation, setShowAllEducation)}
          {getEducationView('Certificates', certificates, showAllCertificates, setShowAllCertificates)}

          <div className="row justify-content-center resume-grouping">
            <div className="col-md-4 padded-right">
              <div className="section-title main-title">
                <h1>Awards</h1>
              </div>
            </div>
            <div className="col-md-8">
              {awards.map((award, index) => {
                return (
                  <div key={`award-${index}`}>
                    <div className={`listing ${award.collapsed && !showAllAwards ? 'collapsed-item' : ''}`}>
                      <div className="listing-title">
                        <span>{award.name}</span>
                      </div>
                      <div className="listing-subtitle">{award.issuer}, {award.location}; {getDateStringValue(award.issueDate)}</div>
                      <div className="listing-description">{award.description}</div>
                    </div>
                  </div>
                );
              })}
              {!showAllAwards && <a href="" onClick={event => handleShowMore(event, setShowAllAwards)}>Show more</a>}
            </div>
          </div>
        </>
      );
    }
  };

  return (
    <section className="section_gap resume_area" id="resume">
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-lg-6 text-center">
            <div className="main-title">
              <h1>My Résumé</h1>
              <p>
                My most recent education and job experiences are listed here chronologically and you can also download a PDF version if you prefer.
                <br />
                <br />
              </p>
              <a href="/assets/documents/David Bradshaw Resume.pdf" target="_blank" className="primary-btn">Download résumé</a>
            </div>
          </div>
        </div>
        <div className="resume_content">{getMainView()}</div>
      </div>
    </section>
  );
}

// src/app/resume/resume.component.ts
import { Component, OnInit } from '@angular/core';
import { SharedService } from '../services/shared.service';
import { ExperienceItem, EducationItem, AwardItem } from '../models/models';
import { ApiService } from '../services/api.service';
import { mergeMap, map } from 'rxjs/operators';

@Component({
  selector: 'app-resume',
  templateUrl: './resume.component.html',
  styleUrls: ['./resume.component.scss']
})
export class ResumeComponent implements OnInit {
  pageStatus: ''|'error'|'loading' = 'loading';
  experiences: Array<ExperienceItem> = [];
  educations: Array<EducationItem> = [];
  certificates: Array<EducationItem> = [];
  awards: Array<AwardItem> = [];
  viewData = {
    education: {
      hasMore: false,
      visible: false,
    },
    experience: {
      hasMore: false,
      visible: false,
    },
    certificate: {
      hasMore: false,
      visible: false,
    },
    award: {
      hasMore: false,
      visible: false,
    }
  };

  constructor(
    private sharedService: SharedService,
    private apiService: ApiService
  ) { }

  ngOnInit() {
    this.pageStatus = 'loading';
    this.sharedService.setPageTitle('Resume');
    this.sharedService.setCurrentPage(this.sharedService.getNavItemByRoute('/resume'));
    this.sharedService.setCurrentBreadcrumbs([
      this.sharedService.getNavItemByRoute('/'),
      this.sharedService.getNavItemByRoute('/resume')
    ]);

    this.apiService.getData('educations').pipe(mergeMap((educationData: Array<EducationItem>) => {
      this.educations = educationData.map(education => {
        education.displayDateString = this.getDateString(education.startDate, education.endDate);
        if (education.collapsed) {
          this.viewData.education.hasMore = true;
        }
        return education;
      });
      return this.apiService.getData('certificates').pipe(mergeMap((certificateData: Array<EducationItem>) => {
        this.certificates = certificateData.map(certificate => {
          certificate.displayDateString = this.getDateString(certificate.startDate, certificate.endDate);
          if (certificate.collapsed) {
            this.viewData.certificate.hasMore = true;
          }
          return certificate;
        });
        return this.apiService.getData('experiences').pipe(mergeMap((experienceData: Array<ExperienceItem>) => {
          this.experiences = experienceData.map(experience => {
            if (Array.isArray(experience.roles)) {
              experience.roles.forEach(role => {
                role.displayDateString = this.getDateString(role.startDate, role.endDate);
              });
            }
            experience.displayDateString = this.getDateString(experience.startDate, experience.endDate);
            if (experience.collapsed) {
              this.viewData.experience.hasMore = true;
            }
            return experience;
          });
          return this.apiService.getData('awards').pipe(map((awardData: Array<AwardItem>) => {
            this.awards = awardData.map(award => {
              award.displayDateString = this.getDateStringValue(new Date(award.issueDate));
              if (award.collapsed) {
                this.viewData.award.hasMore = true;
              }
              return award;
            });
          }));
        }));
      }));
    })).subscribe({
      next: () => {
        this.pageStatus = '';
      },
      error: error => {
      this.sharedService.handleError('Unable to get resume items', error);
      this.pageStatus = 'error';
      }
    });
  }

  showMore = (type: 'experience'|'certificate'|'education'|'award', event: MouseEvent): void => {
    event.preventDefault();
    this.viewData[type].visible = true;
    this.viewData[type].hasMore = false;
  };

  private getDateStringValue(date: Date): string {
    const dateOptions = {year: 'numeric' as 'numeric', month: 'short' as 'short'};
    return date.toLocaleDateString('en-us', dateOptions);
  }

  private getDateString(startDate: string, endDate: string): string {
    const start = new Date(startDate);
    const end = endDate ? new Date(endDate) : null;
    return `${this.getDateStringValue(start)} - ${end ? this.getDateStringValue(end) : 'Present'}`;
  }

}

<section class="section_gap resume_area" id="resume">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 text-center">
        <div class="main-title">
          <h1>My Résumé</h1>
          <p>
            My most recent education and job experiences are listed here chronologically and you can also download a PDF version if you prefer.
            <br>
              <br>
              </p>
              <a href="/assets/documents/David Bradshaw Resume.pdf" target="_blank" class="primary-btn">Download résumé</a>
            </div>
          </div>
        </div>
        <div class="reusme_content">
          @if (pageStatus==='loading') {
            <app-loading></app-loading>
          }
          @if (pageStatus==='error') {
            <app-error></app-error>
          }
          @if (!pageStatus) {
            <div class="row justify-content-center resume-grouping">
              <div class="col-md-4 padded-right">
                <div class="section-title main-title">
                  <h1>Experience</h1>
                </div>
              </div>
              <div class="col-md-8">
                @for (experience of experiences; track experience) {
                  <div class="listing" [ngClass]="{'collapsed-item': experience.collapsed && !viewData.experience.visible}">
                    <div class="listing-title">{{experience.jobTitle}}</div>
                    <div class="listing-subtitle">{{experience.company}}, {{experience.location}}; {{experience.displayDateString}}</div>
                    @if (experience.roles) {
                      <div class="listing-roles">
                        @for (role of experience.roles; track role) {
                          <div class="listing-roles--item">{{role.displayDateString}} &mdash; {{role.jobTitle}}</div>
                        }
                      </div>
                    }
                    <div class="listing-description">{{experience.description}}</div>
                  </div>
                }
                @if (viewData.experience.hasMore) {
                  <a href="" (click)="showMore('experience', $event)">Show more</a>
                }
              </div>
            </div>
            <div class="row justify-content-center resume-grouping">
              <div class="col-md-4 padded-right">
                <div class="section-title main-title">
                  <h1>Education</h1>
                </div>
              </div>
              <div class="col-md-8">
                @for (education of educations; track education) {
                  <div class="listing" [ngClass]="{'collapsed-item': education.collapsed && !viewData.education.visible}">
                    <div class="listing-title">
                      <span>{{education.degree}} {{education.program ? 'in' : ''}} {{education.program}}</span>
                      @if (!education.endDate) {
                        <i class="fa fa-asterisk listing-note" title="In progress"></i>
                      }
                    </div>
                    <div class="listing-subtitle">{{education.school}}, {{education.location}}; {{education.displayDateString}}</div>
                    <div class="listing-description">{{education.description}}</div>
                  </div>
                }
                @if (viewData.education.hasMore) {
                  <a href="" (click)="showMore('education', $event)">Show more</a>
                }
              </div>
            </div>
            <div class="row justify-content-center resume-grouping">
              <div class="col-md-4 padded-right">
                <div class="section-title main-title">
                  <h1>Certificates</h1>
                </div>
              </div>
              <div class="col-md-8">
                @for (certificate of certificates; track certificate) {
                  <div class="listing" [ngClass]="{'collapsed-item': certificate.collapsed && !viewData.certificate.visible}">
                    <div class="listing-title">
                      <span>{{certificate.degree}} {{certificate.program ? 'in' : ''}} {{certificate.program}}</span>
                      @if (!certificate.endDate) {
                        <i class="fa fa-asterisk listing-note" title="In progress"></i>
                      }
                    </div>
                    <div class="listing-subtitle">{{certificate.school}}, {{certificate.location}}; {{certificate.displayDateString}}</div>
                    <div class="listing-description">{{certificate.description}}</div>
                  </div>
                }
                @if (viewData.certificate.hasMore) {
                  <a href="" (click)="showMore('certificate', $event)">Show more</a>
                }
              </div>
            </div>
            <div class="row justify-content-center resume-grouping">
              <div class="col-md-4 padded-right">
                <div class="section-title main-title">
                  <h1>Awards</h1>
                </div>
              </div>
              <div class="col-md-8">
                @for (award of awards; track award) {
                  <div class="listing" [ngClass]="{'collapsed-item': award.collapsed && !viewData.award.visible}">
                    <div class="listing-title">
                      <span>{{award.name}}</span>
                    </div>
                    <div class="listing-subtitle">{{award.issuer}}, {{award.location}}; {{award.displayDateString}}</div>
                    <div class="listing-description">{{award.description}}</div>
                  </div>
                }
                @if (viewData.award.hasMore) {
                  <a href="" (click)="showMore('award', $event)">Show more</a>
                }
              </div>
            </div>
          }
        </div>
      </div>
    </section>
